version: '3.1'

services:
  postgres:
    container_name: postgres_container_diploma
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: diploma
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped
  latex-compiler-rest:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
