version: '3.1'

services:
  postgres:
    container_name: postgres_container_diploma
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: diploma
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    # networks:
    #   - postgres
    restart: unless-stopped
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio:/data
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=changeme
      - MINIO_VOLUMES="/data"
  latex-compiler-rest:
    depends_on:
      - postgres
      - minio
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env.docker
    ports:
      - "8888:8000"
# networks:
#   postgres:
#     driver: bridge
volumes:
  postgres:
  minio:
